---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/mkcert --version
    register: mkcert_test_output
  - name: mkcert --version
    debug:
      msg: '{{ mkcert_test_output.stdout }}'
