---
- name: Testing andrewrothstein.mkcert
  hosts: all
  tasks:
    - name: Installing andrewrothstein.mkcert
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'mkcert --version'
      ansible.builtin.command: mkcert --version
      changed_when: false
      register: mkcert_test_output
    - name: Output from 'mkcert --version'
      ansible.builtin.debug:
        msg: '{{ mkcert_test_output.stdout }}'
